apps/ambassador/urls.py
from django.conf.urls import patterns, url

from util.constants import USERNAME_URL_PATTERN

from ambassador.views import (AmbassadorRedirectView, DashboardView,
	SettingsView, PromoView, PluginView)


urlpatterns = patterns("",
	url(r"^$",
		DashboardView.as_view(),
		name="dashboard"),
	url(r"^settings/$",
		SettingsView.as_view(),
		name="settings"),
	url(r"^promo/$",
		PromoView.as_view(),
		name="promo"),
	url(r"^{}/plugin/$".format(USERNAME_URL_PATTERN),
		PluginView.as_view(),
		name="plugin"),
	url(r"^{}/$".format(USERNAME_URL_PATTERN),
		AmbassadorRedirectView.as_view(),
		name="front_page"),
	url(r"^{}/tour/$".format(USERNAME_URL_PATTERN),
		AmbassadorRedirectView.as_view(),
		name="tour"),
	url(r"^{}/signup/$".format(USERNAME_URL_PATTERN),
		AmbassadorRedirectView.as_view(),
		name="signup"),
	url(r"^{}/signup/plugin/$".format(USERNAME_URL_PATTERN),
		AmbassadorRedirectView.as_view(),
		name="signup_plugin"),
	url(r"^{}/massage-therapist-soap-notes/$".format(USERNAME_URL_PATTERN),
		AmbassadorRedirectView.as_view(),
		name="landing_page_notes")
)

apps/intake_forms/urls.py
from django.conf.urls import patterns, url

from account_hs.authentication import user_authenticated
from intake_forms.views import (IntakeFormAnswersList, intake_form,
	question_edit, ViewIntakeFormAnswer, intake_form_change, question_delete,
	intake_form_answer, SendIntakeForm)

urlpatterns = patterns('',
	url(r"^$", user_authenticated(IntakeFormAnswersList.as_view()), name='intake_forms_list'),

	url(r"^edit/$", intake_form, name='intake_form'),

	url(r"^edit/(?P<question_id>[0-9]+)/$",
		question_edit,
		name='intake_form_question_edit'),

	url(r"^answer/healers/(?P<healer>[\w\._-]+)/clients/(?P<client>[\w\._-]+)/$",
		user_authenticated(ViewIntakeFormAnswer.as_view()),
		name='view_intake_form_answer'),

	url(r"^answer/healers/$", 'util.views.page_not_found',
		name='view_intake_form_answer'),

	url(r"^change/$", intake_form_change, name='intake_form_change'),

	url(r"^delete/(?P<question_id>[0-9]+)/$",
		question_delete,
		name='intake_form_question_delete'),

	url(r"^send/$", SendIntakeForm.as_view(), name="send_intake_form"),

	url(r"^(?P<username>[\w\._-]+)/$",
		intake_form_answer,
		name='intake_form_answer'),
)

apps/payments/urls.py
from django.conf.urls import patterns, url

from account_hs.authentication import user_authenticated
from .views import (HistoryView, StripeConnectPayments, MarkUnpaid, MarkPaid,
	Charge, SaveCard, ClientAppointments, SaveAccountSettings)


urlpatterns = patterns(
	'payments.views',
	url(r'^$', 'stripe_connect_payments', name='stripe_connect_payments'),

	url(r'^save/account_settings$', SaveAccountSettings.as_view(), name='payments_save_account_settings'),
	url(r'^save/card$', SaveCard.as_view(), name='payments_save_card'),
	url(r'^remove/card$', 'remove_card', name='payments_remove_card'),
	url(r'^history/$',
		user_authenticated(HistoryView.as_view()),
		name='payments_history'),

	url(r'^stripe_connect/load/$', StripeConnectPayments.as_view(), name='stripe_connect_load_payments'),
	url(r'^stripe_connect/mark_unpaid/$', MarkUnpaid.as_view(), name='stripe_connect_mark_unpaid'),
	url(r'^stripe_connect/mark_paid/$', MarkPaid.as_view(), name='stripe_connect_mark_paid'),
	url(r'^stripe_connect/charge/$', Charge.as_view(), name='stripe_connect_charge'),
	url(r'^stripe_connect/client_appointments/$', ClientAppointments.as_view(), name='stripe_connect_client_appointments'),

	url(r'^disable_stripe_connect/$', 'disable_stripe_connect', name='disable_stripe_connect'),
	url(r'^stripe_connect_success/$', 'stripe_connect_success', name='stripe_connect_success'),

	# url(r"^webhook/$", "webhook", name="payments_webhook"),

	# url(r"^a/subscribe/$", "subscribe", name="payments_ajax_subscribe"),
	# url(r"^a/change/plan/$", "change_plan", name="payments_ajax_change_plan"),
	# url(r"^a/cancel/$", "cancel", name="payments_ajax_cancel"),
	# url(
	#	 r"^subscribe/$",
	#	 login_required(SubscribeView.as_view()),
	#	 name="payments_subscribe"
	# ),
	# url(
	#	 r"^change/plan/$",
	#	 login_required(ChangePlanView.as_view()),
	#	 name="payments_change_plan"
	# ),
	# url(
	#	 r"^cancel/$",
	#	 login_required(CancelView.as_view()),
	#	 name="payments_cancel"
	# ),
)

urls.py
	url(r"^login/$", "pinax.apps.account.views.login", name="login_page", kwargs={"form_class": LoginFormHS}),
	url(r"^logout/$", "django.contrib.auth.views.logout", {"template_name": "account/logged_out.html"}, name="logout_page"),
	url(r'^captcha/', include('captcha.urls')),

	# password reset
	url(r"^password_reset/$", "clients.views.password_reset", name="acct_passwd_reset"),
	url(r"^password_reset/done/$", "pinax.apps.account.views.password_reset_done", name="acct_passwd_reset_done"),
	url(r"^password_reset_key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
		"pinax.apps.account.views.password_reset_from_key",
		{'form_class': PasswordLengthResetPasswordKeyForm},
		name="acct_passwd_reset_key"),


	url(r"^payments/", include("payments.urls")),
	url(r"^provider/", include("healers.urls")),
	url(r"^events/", include("events.urls")),
	url(r"^client/", include("clients.urls")),
	url(r"^contacts/", include("contacts_hs.urls")),
	url(r"^phonegap/", include("phonegap.urls")),

	url(r"^schedule/", include("schedule.urls")),
	url(r"^sync/", include("sync_hs.urls")),
	url(r"^notes/", include("client_notes.urls")),

	#	 url(r"^healers/$", "healers.views.friends", name="clients_healers", kwargs={"friend_type":"healers"}),
	#	 url(r"^referrals/$", "healers.views.friends", name="referrals", kwargs={"friend_type":"referrals"}),
	#	 url(r"^clients/$", "healers.views.friends", name="clients", kwargs={"friend_type":"clients"}),
	#	 url(r"^search/(?P<friend_type>referrals|clients|healers)$", "healers.views.friends_search", name="friends_search"),
	#	 url(r"^friends/$", include("friends_hs.urls")),
	# url(r"^refer/(?P<provider_username>[\w\._-]+)/clients/$", 'healers.views.clients', name="refer_clients_list"),
	# url(r"^refer/(?P<client_username>[\w\._-]+)/providers/$", 'healers.views.providers', name="refer_providers_list"),
	url(r"^refer/(?P<provider_username>[\w\._-]+)/(?P<client_username>[\w\._-]+)/client/$",
		'healers.views.refer_client',
		name="refer_from_providers"),
	url(r"^refer/(?P<provider_username>[\w\._-]+)/(?P<client_username>[\w\._-]+)/provider/$",
		'healers.views.refer_client',
		kwargs={'email_to_provider': False},
		name="refer_from_clients"),
	url(r"^(?P<friend_type>referrals|clients|healers|providers)/", include("friends_hs.urls")),
#	url(r"^invite/healers_admin/$", "friends_app.views.invite", kwargs={"invite_type": "provider"}, name="invite_healer"),
#	url(r"^home/$", "healers.views.healers_geosearch", name="home"),


	url(r"^reviews/", include("review.urls")),
	url(r"^gratitude_stream/", include("gratitude_stream.urls")),
	url(r"^appointments/$", "clients.views.appointments", name="receiving_appointments"),
	url(r"^appointments/cancel/(?P<appt_id>[0-9]+)$", "clients.views.appointment_cancel", name="appointment_cancel"),
	url(r"^appointments/reschedule/(?P<appt_id>[0-9]+)$", "clients.views.appointment_cancel", kwargs={'action': 'reschedule'}, name="appointment_reschedule"),

	url(r"^login_redirect/", "minidetector.views.login_redirect", name="login_redirect"),

	url(r"^emailconfirmation/(\w+)", "clients.views.confirm_email", name="emailconfirmation_confirm_email"),

	url(r"^oauth/", include("oauth_access.urls")),

	url(r"^autocomplete/", include("autocomplete_hs.urls")),

	url(r"^specialties/", include("modality.urls")),

	url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),

	url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),

	url(r"^iframe_test/$", IframeTest.as_view(), name="iframe_test"),

	url(r"^disable_reminders/", "clients.views.disable_reminders", name="disable_reminders"),

	url(r"^videos/$", "clients.views.videos_list", name="videos_list_all"),
	url(r"^videos/(?P<username>[\w\._-]+)/$", "clients.views.videos_list", name="videos_list_user"),

	url(r"^tshirt/$",
		TemplateView.as_view(template_name='about/tshirt.html'),
		name='tshirt'),

	url(r"^intake_form/", include("intake_forms.urls")),

	url(r"^messagelog/$", "clients.views.messagelog"),
	url(r"^messagelog/failures/$", "clients.views.messagelog", kwargs={"failures": True}),

	url(r"^healing_requests/", include("healing_requests.urls")),

	url(r'^impersonate/(?P<username>[\w\._-]+)/$', "util.views.impersonate", name='impersonate'),
	url(r"^delete_account/$", "account_hs.views.delete", name='delete_account'),
	url(r"^delete_account/(?P<username>[\w\._-]+)/$", "account_hs.views.delete", name='delete_account'),

	url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': healersource_sitemap}),

	#reserved urls - remove any that are < 6 chars for performance reasons
#	url(r"^blog/$", "django.views.defaults.page_not_found"),
	url(r"^reference/$", "django.views.defaults.page_not_found"),
#	url(r"^wiki/$", "django.views.defaults.page_not_found"),
#	url(r"^shop/$", "django.views.defaults.page_not_found"),
#	url(r"^store/$", "django.views.defaults.page_not_found"),
#	url(r"^info/$", "django.views.defaults.page_not_found"),
	url(r"^information/$", "django.views.defaults.page_not_found"),
#	url(r"^help/$", "django.views.defaults.page_not_found"),
	url(r"^contact/$", "django.views.defaults.page_not_found"),
#	url(r"^news/$", "django.views.defaults.page_not_found"),
#	url(r"^book/$", "django.views.defaults.page_not_found"),
	url(r"^booking/$", "django.views.defaults.page_not_found"),
	url(r"^bookings/$", "django.views.defaults.page_not_found"),
	url(r"^offers/$", "django.views.defaults.page_not_found"),
	url(r"^pricing/$", "django.views.defaults.page_not_found"),
#	url(r"^intro/$", "django.views.defaults.page_not_found"),
	url(r"^introduction/$", "django.views.defaults.page_not_found"),
#	url(r"^gift/$", "django.views.defaults.page_not_found"),
	url(r"^gift_certificate/$", "django.views.defaults.page_not_found"),
	url(r"^gift_certificates/$", "django.views.defaults.page_not_found"),
	url(r"^service/$", "django.views.defaults.page_not_found"),
	url(r"^services/$", "django.views.defaults.page_not_found"),
#	url(r"^apply/$", "django.views.defaults.page_not_found"),
#	url(r"^jobs/$", "django.views.defaults.page_not_found"),
#	url(r"^press/$", "django.views.defaults.page_not_found"),
#	url(r"^faq/$", "django.views.defaults.page_not_found"),
#	url(r"^feed/$", "django.views.defaults.page_not_found"),
#	url(r"^rss/$", "django.views.defaults.page_not_found"),
	url(r"^addons/$", "django.views.defaults.page_not_found"),
	url(r"^articles/$", "django.views.defaults.page_not_found"),
	url(r"^treatments/$", "django.views.defaults.page_not_found"),
#	url(r"^spa/$", "django.views.defaults.page_not_found"),
	url(r"^school/$", "django.views.defaults.page_not_found"),
	url(r"^schools/$", "django.views.defaults.page_not_found"),
	url(r"^calendar/$", "django.views.defaults.page_not_found"),
	url(r"^condition/$", "django.views.defaults.page_not_found"),
	url(r"^symptom/$", "django.views.defaults.page_not_found"),
	url(r"^symptoms/$", "django.views.defaults.page_not_found"),
#	url(r"^soap/$", "django.views.defaults.page_not_found"),
#	url(r"^wall/$", "django.views.defaults.page_not_found"),
	url(r"^inspiration/$", "django.views.defaults.page_not_found"),
	url(r"^inspirations/$", "django.views.defaults.page_not_found"),
	url(r"^history/$", "django.views.defaults.page_not_found"),
	url(r"^groups/$", "django.views.defaults.page_not_found"),
	url(r"^circles/$", "django.views.defaults.page_not_found"),
#	url(r"^trade/$", "django.views.defaults.page_not_found"),
	url(r"^trades/$", "django.views.defaults.page_not_found"),
	url(r"^connect/$", "django.views.defaults.page_not_found"),
	url(r"^connection/$", "django.views.defaults.page_not_found"),
	url(r"^connections/$", "django.views.defaults.page_not_found"),
	url(r"^health/$", "django.views.defaults.page_not_found"),
	url(r"^healing/$", "django.views.defaults.page_not_found"),
	url(r"^newsletter/$", "django.views.defaults.page_not_found"),
	url(r"^mailing_list/$", "django.views.defaults.page_not_found"),
	url(r"^mailing_lists/$", "django.views.defaults.page_not_found"),
	url(r"^shirts/$", "django.views.defaults.page_not_found"),
	url(r"^tshirts/$", "django.views.defaults.page_not_found"),
	url(r"^apparel/$", "django.views.defaults.page_not_found"),
	url(r"^google/$", "django.views.defaults.page_not_found"),
	url(r"^facebook/$", "django.views.defaults.page_not_found"),
	url(r"^twitter/$", "django.views.defaults.page_not_found"),
	url(r"^linkedin/$", "django.views.defaults.page_not_found"),
	url(r"^linked_in/$", "django.views.defaults.page_not_found"),
	url(r"^instagram/$", "django.views.defaults.page_not_found"),
#	url(r"^table/$", "django.views.defaults.page_not_found"),
#	url(r"^other/$", "django.views.defaults.page_not_found"),
	url(r"^empty/$", lambda request: HttpResponse(""), name="empty_page"),
	url(r"^healing-circle/", include("send_healing.urls")),
	url(r"^global_healing_project/", RedirectView.as_view(pattern_name='send_healing')),
	url(r"^(?P<username>[\w\._-]+)/$", "healers.views.healer", name="healer_my_profile"),
	url(r"^(?P<username>[\w\._-]+)/service/(?P<treatment_type>[\w\._-]+)/$", "healers.views.healer", name="healer_my_profile"),
	url(r"^(?P<username>[\w\._-]+)/(?P<location>[\w\._-]+)/$", "healers.views.healer", name="healer_public_profile"),

	url(r"^(?P<city>[\w\._-]+)/(?P<specialty>[\w\._-]+)/"
		r"(?P<username>[\w\._-]+)/$",
		"healers.views.healer", name="healer_public_profile"),

	url(r"^(?P<city>[\w\._-]+)/(?P<specialty>[\w\._-]+)/"
		r"(?P<username>[\w\._-]+)/(?P<treatment_type>[\w\._-]+)/$",
		"healers.views.healer", name="healer_public_profile"),

)

urlpatterns += staticfiles_urlpatterns()

# if settings.ENABLE_ADMIN_URLS:
# 	urlpatterns = patterns("",
# 		url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
# 		url(r"^admin/", include(admin.site.urls)),
# 	) + urlpatterns

if settings.SERVE_MEDIA:
	urlpatterns += patterns(
		'',
		# url(r'', include("staticfiles.urls")),
		(r'^site_media/media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	)

try:

apps/intake_forms/models.py
from django.db import models
from django.core.exceptions import ValidationError
from encrypted_fields import EncryptedTextField


class IntakeForm(models.Model):
	"""
	Form with a series of questions to ask clients
	"""

	ANSWER_STORE_ON_SITE = 0
	ANSWER_ON_SITE_SEND_BY_EMAIL = 1
	ANSWER_BY_EMAIL = 2
	ANSWER_OPTION_CHOICES = (
		(ANSWER_BY_EMAIL,
			'Send intake form to client by email (this will send the client '
			'an email containing all questions, and they will email their '
			'responses to you)'),
		(ANSWER_ON_SITE_SEND_BY_EMAIL,
			'Client fills out intake form on HealerSource, and the responses '
			'are sent to me in an email. This will not store any of '
			'the client\'s information on HealerSource'),
		(ANSWER_STORE_ON_SITE, 'Store Intake form in HealerSource'),
	)

	healer = models.ForeignKey('healers.Healer', related_name='intake_forms')
	answer_option = models.PositiveSmallIntegerField(
		default=ANSWER_STORE_ON_SITE,
		choices=ANSWER_OPTION_CHOICES)

	created_at = models.DateTimeField(auto_now_add=True)


class Question(models.Model):
	"""
	Question for intake form
	"""

	form = models.ForeignKey(IntakeForm, related_name='questions')
	text = models.TextField()
	is_required = models.BooleanField(default=True)
	#the height of the textarea the client will be given to answer the question
	answer_rows = models.PositiveSmallIntegerField(
		default=1,
		choices=[(i, i) for i in range(1, 11)])

	def __unicode__(self):
		return self.text

	@property
	def text_with_optional_message(self):
		text = self.text
		if not self.is_required:
			text += ' (optional)'
		return text


class Answer(models.Model):
	"""Client's answer info for intake form."""
	client = models.ForeignKey('clients.Client', related_name='intake_form_answers')
	form = models.ForeignKey(IntakeForm)
	date = models.DateTimeField(auto_now=True)

	def save(self, *args, **kwargs):
		super(Answer, self).save(*args, **kwargs)


class AnswerResult(models.Model):
	"""Client's answer text."""
	answer = models.ForeignKey(Answer, related_name='results')
	question = models.ForeignKey(Question, related_name='results')
	text = EncryptedTextField(blank=True)


class IntakeFormSentHistory(models.Model):
	'''
	A record is saved whenever healer sends intake form to client
	'''
	client = models.ForeignKey('clients.Client', related_name='intake_form_sent_history_client')
	healer = models.ForeignKey('healers.Healer', related_name='intake_form_sent_history_healer')
	created_at = models.DateTimeField(auto_now_add=True)
	modified_at = models.DateTimeField(auto_now=True)

templates/intake_forms/answer.html
{% extends "site_base.html" %}

{% block head_title %}{{ healer_name }}'s Intake Form{% endblock %}

{% block page_title %}<h1 class="nav_icon nav_intake">{{ healer_name }}'s Intake Form</h1>{% endblock %}

{% block body %}

	{% if success %}
		<p class="message">Thanks for filling in {{ healer_name }}'s Intake Form!</p>
	{% else %}

		{% if is_concierge %}
			<div class="single_button message" style="margin-left: 0;">Please fill in this brief Intake Form so that {{ healer_name }} can serve you better.</div>
		{% endif %}

		{% include "form_errors.html" %}

		<form id="intake_answer_form" action="." method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<p><input type="submit" value="Submit Form" /></p>
		</form>
	{% endif %}

{% endblock %}

templates/intake_forms/intake_form.html
{% extends "site_base.html" %}

{% block head_title %}Edit Intake Form{% endblock %}

{% block page_title %}<h1 class="nav_icon nav_intake">Edit Intake Form</h1>{% endblock %}

{% block body %}

		{% if questions %}
			<div class="grey_box">
				<h3>Questions</h3>
				<div id="intake_forms_questions">
					{% for question in questions %}
						<p>
							<strong>{{ question.text_with_optional_message }}</strong>
							| <a href="{% url 'intake_form_question_edit' question.id %}">edit</a>
							| <a href="{% url 'intake_form_question_delete' question.id %}">delete</a>
							<br/>
							<textarea class="disabled" disabled rows="{{ question.answer_rows }}"></textarea>
						</p>
					{% endfor %}
				</div>
			</div>
			<hr/>
		{% else %}
			<p class="message">Your intake form doesn't have any questions yet. Add one below to get started.</p>
		{% endif %}
		<div class="add_box" style="width: 95%;">
			<h3>+ Create a New Question</h3>
			{% with add_question_form as form %}
				{% include "form_errors.html" %}
			{% endwith %}
			<form action="." method="post">
				{% csrf_token %}
				<table style="width:100%;">
					{{ add_question_form.as_table }}
				</table>
				<input type="submit" value="Add Question" />
			</form>
		</div>

		<div class="clearfix"></div>

		{% if questions %}
			<p><a href="{% url 'intake_forms_list' %}">&laquo; Done Editing</a></p>
		{% endif %}

	<div class="clearfix"></div>

{% endblock %}

templates/intake_forms/intake_form_answer_list.html
{% extends 'site_base.html' %}

{% load compress %}

{% block head_title %}Intake Forms{% endblock %}

{% block extra_head %}
	{% compress js %}
		<script type="text/javascript">
			var url_send_intake_form = "{% url 'send_intake_form' %}";
			var list_intake_forms_page = true;
			var clients = {{ clients|safe }};
			var username = '';

			$(document).ready(function(){
				initClientSearchAutocomplete();
				initNewClientDialog();
			});
		</script>
		<script type="text/javascript" src='{{ STATIC_URL }}healersource/js/weekcalendar-schedule.js'></script>
		<script src="{{ STATIC_URL }}healersource/js/invite.js"></script>
	{% endcompress %}
	{% compress css %}
		<!-- used for client form styles -->
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}healersource/css/healer-weekcalendar.css" />
	{% endcompress %}

{% endblock %}

{% block page_title %}<h1 class="nav_icon nav_intake">Intake Forms</h1>{% endblock %}

{% block body %}

	<div>
		<a class="highlight_button nav_icon nav_pencil" href="{% url 'intake_form' %}" style="margin-bottom: 8px;;">Edit Intake Form</a>
		<input type="hidden" id="id_client" />
		<a href="#" onclick="dlg_new_client();" class="intake_form_new_client">+ New Client</a>
		<div class='float_right grey_box pale_yellow_box search_box'>
			<span class="nav_icon nav_find_a_provider">Send intake form to: <input type='text' data-page='list_intake_forms_page' id='search_client' placeholder='Client name or last name' style="width: 150px;"/></span>
		</div>

	</div>
	{% include "healers/new_client_dialog.html" %}
	<div class='clearfix' style="margin-bottom: 6px;"></div>


	<h3>Completed Forms</h3>
	{% if complete_forms %}
		<table class="client_list responsive_table">
			{% for answer in complete_forms %}
				<tr>
					<td>
						<a class='floatbox' data-fb-options='type:ajax' href="{% url 'view_intake_form_answer' healer.user.username  answer.client.user.username %}">{{ answer.client }}</a>
					</td>
					{#						<td>{{ answer.date }}</td>#}
				</tr>
			{% endfor %}
		</table>
	{% else %}
		<p class="message">No answered intake forms.</p>
	{% endif %}


	<h3>Incomplete forms</h3>
	{% if incomplete_forms %}
		<table class="client_list responsive_table">
			{% for history in incomplete_forms %}
				<tr>
					<td>
						<a href='{% url 'client_detail' history.client.user.username %}' class="client_detail floatbox" data-fb-options="type:ajax">{{ history.client }}</a>
						&nbsp;|&nbsp;
						<a href="javascript:void(0);" onclick="send_intake_form({{ history.client.pk }})">Resend &raquo;</a>
					</td>
					{#						<td>{{ history.created_at }}</td>#}
				</tr>
			{% endfor %}
		</table>
	{% else %}
		<p class="message">No unanswered forms.</p>
	{% endif %}
{% endblock %}

templates/intake_forms/question_edit.html
{% extends "site_base.html" %}

{% block head_title %}Edit Location{% endblock %}

{% block page_title %}<h1>Edit Question</h1>{% endblock %}

{% block body %}

	{% include "form_errors.html" %}

	<form action="{% url 'intake_form_question_edit' form.instance.id %}" method="post">
		{% csrf_token %}
		<table class="no_wrap">
			{{ form.as_table }}
		</table>
		<p><input type="submit" value="Save Question" /></p>
	</form>

	<p><a href="{% url 'intake_form' %}">&laquo; Back to Intake Form</a></p>

{% endblock %}

templates/intake_forms/view_intake_form_answer.html
<h3 class="nav_icon nav_intake">{{ client }}</h3>

{% for key in qa %}
	<p><strong>{{ key.question }}</strong></p>
	<p style="margin-left: 10px;">{{ key.answer }}</p>
{% endfor %}