apps/about/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from about.views import SearchAjax, CitySelectCode, FeaturedProviders, GeoSpecialties, ContactUs


urlpatterns = patterns(
	'about.views.homepage',
	url(r'^$', 'front_page', name='front_page'),
	url(r'^home/$', 'homepage', name='home'),
)

urlpatterns += patterns(
	'about.views',
	url(r'^wcenter/', 'wcenter', name='wellness_center_list'),
	url(r'^concierge/(?P<username>[\w\._-]+)/thanks', 'concierge_thanks', name='concierge_thanks'),

	url(r'^search_ajax', SearchAjax.as_view(), name='search_ajax'),
	url(r'^city_select_code', CitySelectCode.as_view(), name='search_city_select_code'),
	url(r'^featured_providers', FeaturedProviders.as_view(), name='featured_providers'),
	url(r'^geo_specialties', GeoSpecialties.as_view(), name='geo_specialties'),
	url(r'^contact_us', ContactUs.as_view(), name='contact_us'),
	url(r"^report_error/$", "error_report", name="report_error"),

	url(r'^search/infinite/grid/', 'search', {'template_name': 'about/search/results_grid.html'},
		name='search_infinite_grid'),

	url(r'^learn/blog/infinite/', 'learn', name='learn_blog_infinite', kwargs={'only_posts': True}),
	url(r"^featured/$", "featured", name="featured"),
	url(r"^learn/$", "learn", name="learn"),
	url(r"^pricing/$", "pricing", name="pricing"),
	url(r'^tour/$', 'tour', name='tour'),
	url(r'^what_next/$', 'what_next', name='what_next'),
	url(r'^search/(?P<modality>[0-9]+)$', 'search', name='search_modality'),
	url(r'^stats/$', 'search', {'all': 'True'}, name='stats'),
	url(r'^all/healers$', 'all_users', {'healers_only': 'True'}, name='all_healers'),
	url(r'^all/boston$', 'all_users', {'healers_only': 'True', 'boston': 'True'}, name='all_boston'),
	url(r'^all/users$', 'all_users', name='all_users'),

	url(r'^search/$', 'search', name='search_results'),
	url(r'^search/(?P<city>[&\w\s_\-]+)_(?P<state>[\w]{2})/$', 'search', name='search_seo_city2'),
	url(r'^search/(?P<city>[&\w\s_\-]+)/$', 'search', name='search_seo_city'),
	url(r'^search/(?P<city>[&\w\s_\-]+)_(?P<state>[\w]{2})/(?P<specialty>[&\w\W\s_\-]+)/$', 'search', name='search_seo_city_specialty2'),
	url(r'^search/(?P<city>[&\w\s_\-]+)/(?P<specialty>[&\w\W\s_\-]+)/$', 'search', name='search_seo_city_specialty'),

)

urlpatterns += patterns(
	'',
	url(r'^robots\.txt$',
		TemplateView.as_view(template_name='about/robots.txt'),
		name='robots'),

	url(r'^terms_of_service/$',
		TemplateView.as_view(template_name='about/terms.html'),
		name='terms'),

	url(r'^hipaa/$',
		TemplateView.as_view(template_name='about/hipaa.html'),
		name='hipaa'),

	url(r'^hipaa_content/$',
		TemplateView.as_view(template_name='about/hipaa_content.html'),
		name='hipaa_content'),

	url(r'^privacy/$',
		TemplateView.as_view(template_name='about/privacy.html'),
		name='privacy'),

	url(r'^bad_browser/$',
		TemplateView.as_view(template_name='about/bad_browser.html'),
		name='bad_browser'),

	url(r'^schedule_spa/$',
		TemplateView.as_view(template_name='about/schedule_promo_wcenter.html'),
		name='schedule_promo_wcenter'),

	url(r'^partners/$',
		TemplateView.as_view(template_name='about/partners.html'),
		name='partners'),

)


#	url(r'^waitinglist_success/$', direct_to_template, {
#        'template': 'waitinglist/success.html',
#    }, name='waitinglist_success'),
#    url(r'^$', direct_to_template, {
#        'template': 'homepage.html',
#    }, name='home'),
#    url(r'^about/', include('about.urls')),

#    url(r"^$", direct_to_template, {"template": "about/about.html"}, name="about"),
#    url(r"^terms/$", TemplateView.as_view(template_name="about/terms.html"), name="terms"),
#    url(r"^privacy/$", TemplateView.as_view(template_name="about/privacy.html"), name="privacy"),
#    url(r"^dmca/$", direct_to_template, {"template": "about/dmca.html"}, name="dmca"),
#    url(r"^what_next/$", login_required(direct_to_template), {"template": "about/what_next.html"}, name="what_next"),
#    url(r"^what_next/$", "about.views.what_next", name="what_next"),

apps/ambassador/urls.py
from django.conf.urls import patterns, url

from util.constants import USERNAME_URL_PATTERN

from ambassador.views import (AmbassadorRedirectView, DashboardView,
	SettingsView, PromoView, PluginView)


urlpatterns = patterns("",
	url(r"^$",
		DashboardView.as_view(),
		name="dashboard"),
	url(r"^settings/$",
		SettingsView.as_view(),
		name="settings"),
	url(r"^promo/$",
		PromoView.as_view(),
		name="promo"),
	url(r"^{}/plugin/$".format(USERNAME_URL_PATTERN),
		PluginView.as_view(),
		name="plugin"),
	url(r"^{}/$".format(USERNAME_URL_PATTERN),
		AmbassadorRedirectView.as_view(),
		name="front_page"),
	url(r"^{}/tour/$".format(USERNAME_URL_PATTERN),
		AmbassadorRedirectView.as_view(),
		name="tour"),
	url(r"^{}/signup/$".format(USERNAME_URL_PATTERN),
		AmbassadorRedirectView.as_view(),
		name="signup"),
	url(r"^{}/signup/plugin/$".format(USERNAME_URL_PATTERN),
		AmbassadorRedirectView.as_view(),
		name="signup_plugin"),
	url(r"^{}/massage-therapist-soap-notes/$".format(USERNAME_URL_PATTERN),
		AmbassadorRedirectView.as_view(),
		name="landing_page_notes")
)

apps/payments/urls.py
from django.conf.urls import patterns, url

from account_hs.authentication import user_authenticated
from .views import (HistoryView, StripeConnectPayments, MarkUnpaid, MarkPaid,
	Charge, SaveCard, ClientAppointments, SaveAccountSettings)


urlpatterns = patterns(
	'payments.views',
	url(r'^$', 'stripe_connect_payments', name='stripe_connect_payments'),

	url(r'^save/account_settings$', SaveAccountSettings.as_view(), name='payments_save_account_settings'),
	url(r'^save/card$', SaveCard.as_view(), name='payments_save_card'),
	url(r'^remove/card$', 'remove_card', name='payments_remove_card'),
	url(r'^history/$',
		user_authenticated(HistoryView.as_view()),
		name='payments_history'),

	url(r'^stripe_connect/load/$', StripeConnectPayments.as_view(), name='stripe_connect_load_payments'),
	url(r'^stripe_connect/mark_unpaid/$', MarkUnpaid.as_view(), name='stripe_connect_mark_unpaid'),
	url(r'^stripe_connect/mark_paid/$', MarkPaid.as_view(), name='stripe_connect_mark_paid'),
	url(r'^stripe_connect/charge/$', Charge.as_view(), name='stripe_connect_charge'),
	url(r'^stripe_connect/client_appointments/$', ClientAppointments.as_view(), name='stripe_connect_client_appointments'),

	url(r'^disable_stripe_connect/$', 'disable_stripe_connect', name='disable_stripe_connect'),
	url(r'^stripe_connect_success/$', 'stripe_connect_success', name='stripe_connect_success'),

	# url(r"^webhook/$", "webhook", name="payments_webhook"),

	# url(r"^a/subscribe/$", "subscribe", name="payments_ajax_subscribe"),
	# url(r"^a/change/plan/$", "change_plan", name="payments_ajax_change_plan"),
	# url(r"^a/cancel/$", "cancel", name="payments_ajax_cancel"),
	# url(
	#	 r"^subscribe/$",
	#	 login_required(SubscribeView.as_view()),
	#	 name="payments_subscribe"
	# ),
	# url(
	#	 r"^change/plan/$",
	#	 login_required(ChangePlanView.as_view()),
	#	 name="payments_change_plan"
	# ),
	# url(
	#	 r"^cancel/$",
	#	 login_required(CancelView.as_view()),
	#	 name="payments_cancel"
	# ),
)

urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.http import HttpResponse
from django.views.generic import TemplateView, RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.decorators.csrf import csrf_exempt

from account_hs.forms import PasswordLengthResetPasswordKeyForm, LoginFormHS
from account_hs.views import (Signup, SignupClient, Login, UpdateLinkSource,
								FacebookSignup)
from errors_hs.views import ErrorReportView
from oauth2_hs.views import AccessTokenView
from apps.healers.views import IframeTest
from apps.phonegap.views import IsHealer, IsAdmin, Version
from apps.feedback.views import Submit
from apps.messages_hs.views import SendMessage

from sitemap import healersource_sitemap

# if settings.ENABLE_ADMIN_URLS:
# 	from django.contrib import admin
# 	admin.autodiscover()

from dajaxice.core import dajaxice_autodiscover

dajaxice_autodiscover()

handler500 = "apps.server_error"

urlpatterns = patterns('',
	url(r'^', include('about.urls')),
	url(r'^confirmation_required/', include('about.confirmation_required_urls')),

	url(r'^massage-therapist-soap-notes/', 'about.views.landing_page_notes', name='landing_page_notes'),
	url(r'^physical-therapist-soap-notes/', 'about.views.landing_page_notes', name='landing_page_notes_pt'),
	url(r'^occupational-therapist-soap-notes/', 'about.views.landing_page_notes', name='landing_page_notes_ot'),
	url(r'^chiropractor-soap-notes/', 'about.views.landing_page_notes', name='landing_page_notes_chiropractor'),
	url(r'^chiropractors-soap-notes/', 'about.views.landing_page_notes', name='landing_page_notes_chiropractors'),
	url(r'^chiropractic-soap-notes/', 'about.views.landing_page_notes', name='landing_page_notes_chiropractic'),
	url(r'^book/thanks/$', 'about.views.book_thanks', name='book_thanks'),
	url(r'^book/', 'about.views.landing_page_book', name='landing_page_book'),

	url(r'^ambassador/', include('ambassador.urls', namespace='ambassador')),

	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	url(r'^oauth2/', include('provider.oauth2.urls', namespace='oauth2')),
	url(r'^oauth2login/google/', 'oauth2_hs.views.google', name='oauth2_google_login'),
	url(r'^oauth2callback/google/', 'oauth2_hs.views.auth_return'),
	url('^oauth2_facebook/access_token/?$',
		csrf_exempt(AccessTokenView.as_view()), name='access_token'),

	# phonegap links
	url(r'^version/$', Version.as_view(), name='version'),  # for backward compatibility
	url(r'^is_healer/$', IsHealer.as_view(), name='is_healer'),
	url(r'^is_admin/$', IsAdmin.as_view(), name='is_admin'),
	url(r'^phonegap/', include('phonegap.urls')),

	url(r"^facebook_signup/$", FacebookSignup.as_view(), name="ajax_facebook_signup"),

	url(r"^purchase_gift_certificate/(?P<username>[\w\._-]+)/$", "healers.views.purchase_gift_certificate", name="purchase_gift_certificate"),
	url(r"^blog/", include("blog_hs.urls")),
	url(r"^invitations/", include("friends_app.urls")),

	url(r"^submit_feedback/$", Submit.as_view(), name="submit_feedback"),
	url(r"^error_report/$", ErrorReportView.as_view(), name="error_report"),
	url(r"^send_message/$", SendMessage.as_view(), name="send_message"),

	url(r"^signup_client_ajax/$", SignupClient.as_view(), name="ajax_signup_client"),
	url(r"^login_ajax/$", Login.as_view(), name="ajax_login"),

	url(r"^signup/$", "account_hs.views.signup", name="signup"),
	url(r"^signup/plugin/$", "account_hs.views.signup", name="signup_plugin", kwargs={'plugin': True}),
	url(r"^signup_ajax/$", Signup.as_view(), name="ajax_signup"),
	url(r"^signup/thanks_verification/$", "util.views.page_not_found", name="signup_thanks"),
	url(r"^signup/thanks_verification/(?P<type>client|healer|wellness_center)/$", "account_hs.views.signup_thanks", name="signup_thanks"),
	url(r"^signup/thanks/$", "util.views.page_not_found", name="signup_thanks_no_verification"),
	url(r"^signup/thanks/(?P<type>client|healer|wellness_center)/$", "account_hs.views.signup_thanks", name="signup_thanks_no_verification", kwargs={"email_verification": False}),
	url(r'^account/update-link-source/$', UpdateLinkSource.as_view(), name='update_link_source'),
	url(r"^messages/", include("django_messages.urls")),

	url(r"^login/$", "pinax.apps.account.views.login", name="login_page", kwargs={"form_class": LoginFormHS}),
	url(r"^logout/$", "django.contrib.auth.views.logout", {"template_name": "account/logged_out.html"}, name="logout_page"),
	url(r'^captcha/', include('captcha.urls')),

	# password reset
	url(r"^password_reset/$", "clients.views.password_reset", name="acct_passwd_reset"),
	url(r"^password_reset/done/$", "pinax.apps.account.views.password_reset_done", name="acct_passwd_reset_done"),
	url(r"^password_reset_key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
		"pinax.apps.account.views.password_reset_from_key",
		{'form_class': PasswordLengthResetPasswordKeyForm},
		name="acct_passwd_reset_key"),


	url(r"^payments/", include("payments.urls")),
	url(r"^provider/", include("healers.urls")),
	url(r"^events/", include("events.urls")),
	url(r"^client/", include("clients.urls")),
	url(r"^contacts/", include("contacts_hs.urls")),
	url(r"^phonegap/", include("phonegap.urls")),

	url(r"^schedule/", include("schedule.urls")),
	url(r"^sync/", include("sync_hs.urls")),
	url(r"^notes/", include("client_notes.urls")),

	#	 url(r"^healers/$", "healers.views.friends", name="clients_healers", kwargs={"friend_type":"healers"}),
	#	 url(r"^referrals/$", "healers.views.friends", name="referrals", kwargs={"friend_type":"referrals"}),
	#	 url(r"^clients/$", "healers.views.friends", name="clients", kwargs={"friend_type":"clients"}),
	#	 url(r"^search/(?P<friend_type>referrals|clients|healers)$", "healers.views.friends_search", name="friends_search"),
	#	 url(r"^friends/$", include("friends_hs.urls")),
	# url(r"^refer/(?P<provider_username>[\w\._-]+)/clients/$", 'healers.views.clients', name="refer_clients_list"),
	# url(r"^refer/(?P<client_username>[\w\._-]+)/providers/$", 'healers.views.providers', name="refer_providers_list"),
	url(r"^refer/(?P<provider_username>[\w\._-]+)/(?P<client_username>[\w\._-]+)/client/$",
		'healers.views.refer_client',
		name="refer_from_providers"),
	url(r"^refer/(?P<provider_username>[\w\._-]+)/(?P<client_username>[\w\._-]+)/provider/$",
		'healers.views.refer_client',
		kwargs={'email_to_provider': False},
		name="refer_from_clients"),
	url(r"^(?P<friend_type>referrals|clients|healers|providers)/", include("friends_hs.urls")),
#	url(r"^invite/healers_admin/$", "friends_app.views.invite", kwargs={"invite_type": "provider"}, name="invite_healer"),
#	url(r"^home/$", "healers.views.healers_geosearch", name="home"),


	url(r"^reviews/", include("review.urls")),
	url(r"^gratitude_stream/", include("gratitude_stream.urls")),
	url(r"^appointments/$", "clients.views.appointments", name="receiving_appointments"),
	url(r"^appointments/cancel/(?P<appt_id>[0-9]+)$", "clients.views.appointment_cancel", name="appointment_cancel"),
	url(r"^appointments/reschedule/(?P<appt_id>[0-9]+)$", "clients.views.appointment_cancel", kwargs={'action': 'reschedule'}, name="appointment_reschedule"),

	url(r"^login_redirect/", "minidetector.views.login_redirect", name="login_redirect"),

	url(r"^emailconfirmation/(\w+)", "clients.views.confirm_email", name="emailconfirmation_confirm_email"),

	url(r"^oauth/", include("oauth_access.urls")),

	url(r"^autocomplete/", include("autocomplete_hs.urls")),

	url(r"^specialties/", include("modality.urls")),

	url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),

	url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),

	url(r"^iframe_test/$", IframeTest.as_view(), name="iframe_test"),

	url(r"^disable_reminders/", "clients.views.disable_reminders", name="disable_reminders"),

	url(r"^videos/$", "clients.views.videos_list", name="videos_list_all"),
	url(r"^videos/(?P<username>[\w\._-]+)/$", "clients.views.videos_list", name="videos_list_user"),

	url(r"^tshirt/$",
		TemplateView.as_view(template_name='about/tshirt.html'),
		name='tshirt'),

	url(r"^intake_form/", include("intake_forms.urls")),

	url(r"^messagelog/$", "clients.views.messagelog"),
	url(r"^messagelog/failures/$", "clients.views.messagelog", kwargs={"failures": True}),

	url(r"^healing_requests/", include("healing_requests.urls")),

	url(r'^impersonate/(?P<username>[\w\._-]+)/$', "util.views.impersonate", name='impersonate'),
	url(r"^delete_account/$", "account_hs.views.delete", name='delete_account'),
	url(r"^delete_account/(?P<username>[\w\._-]+)/$", "account_hs.views.delete", name='delete_account'),

	url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': healersource_sitemap}),

	#reserved urls - remove any that are < 6 chars for performance reasons
#	url(r"^blog/$", "django.views.defaults.page_not_found"),
	url(r"^reference/$", "django.views.defaults.page_not_found"),
#	url(r"^wiki/$", "django.views.defaults.page_not_found"),
#	url(r"^shop/$", "django.views.defaults.page_not_found"),
#	url(r"^store/$", "django.views.defaults.page_not_found"),
#	url(r"^info/$", "django.views.defaults.page_not_found"),
	url(r"^information/$", "django.views.defaults.page_not_found"),
#	url(r"^help/$", "django.views.defaults.page_not_found"),
	url(r"^contact/$", "django.views.defaults.page_not_found"),
#	url(r"^news/$", "django.views.defaults.page_not_found"),
#	url(r"^book/$", "django.views.defaults.page_not_found"),
	url(r"^booking/$", "django.views.defaults.page_not_found"),
	url(r"^bookings/$", "django.views.defaults.page_not_found"),
	url(r"^offers/$", "django.views.defaults.page_not_found"),
	url(r"^pricing/$", "django.views.defaults.page_not_found"),
#	url(r"^intro/$", "django.views.defaults.page_not_found"),
	url(r"^introduction/$", "django.views.defaults.page_not_found"),
#	url(r"^gift/$", "django.views.defaults.page_not_found"),
	url(r"^gift_certificate/$", "django.views.defaults.page_not_found"),

apps/about/models.py
from django.db import models
from django.dispatch import receiver
from django.utils import timezone
from django.db.models.signals import post_save
from oauth_access.models import UserAssociation


class UserAssociationDated(models.Model):
	user_assoc = models.OneToOneField(UserAssociation, primary_key=True)
	date_created = models.DateTimeField(auto_now_add=timezone.now)


@receiver(post_save, sender=UserAssociation)
def listener(sender, instance, created, **kwargs):
	if created:
		UserAssociationDated.objects.create(user_assoc=instance)

apps/search/views.py
# Create your views here.

templates/about/search/content.html
<form action='{% url 'search_results' %}' method='GET' name="search_form"
	id="healers_form" class="search_form" fire_event="true">
	{% csrf_token %}

	{% with 1 as search_display_button %}
		{% include 'about/search/form_fields.html' %}
	{% endwith %}

	{{ modality_menu|safe }}
</form>

<div class="clearfix"></div>

{% if user.is_superuser or user.is_staff %}
	{% include 'about/stats_admin.html' %}
{% endif %}

{% if message %}
	<p class="message">{{ message }}</p>
{% endif %}

<div id="search_results">
    {% if found_providers %}
        {% with 1 as skip_first_hr %}
            {% include 'about/search/results_list.html' %}
        {% endwith %}
    {% endif %}
    {% include 'about/search/results_not_found.html' %}
</div>

templates/about/search/extra_head.html
{% load compress %}
{% compress js %}
<script type="text/javascript">
	var Modality_Autocomplete_Url = "{% url 'autocomplete_modality_or_category' %}";
	var modality_id = {% if modality_id %}{{ modality_id }}{% else %} '' {% endif %};
	var modality_category_id = {% if modality_category_id %}{{ modality_category_id }}{% else %} '' {% endif %};
	var is_concierge_found = {{ concierge|yesno:"true,false" }};
	var no_find_popup = true;
	var remote_sessions = {{ remote_sessions|yesno:'true,false' }};
	var embed_user = '{% if embed %}{{ embed.username }}{% endif %}';
</script>
<script type="text/javascript" src="{{ STATIC_URL }}healersource/js/search_page.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
{% endcompress %}

templates/about/search/form_fields.html
<div class="field field_zipcode_modality">
	<div class="fields">
		<div>
			{{ search_form.zipcode }}
			{{ search_form.city }}
			{{ search_form.state }}
			{{ search_form.modality_id }}
			{{ search_form.modality_category_id }}
			{{ search_form.search_city_or_zipcode }}
			{{ search_form.modality3 }}
		</div>
	</div>
	{% if embed and not request.user.is_authenticated %}
		<div class="signup_button">
			<a href="{% url 'ambassador:signup_plugin' embed.username %}" class="homepage_button">Sign Up</a>
		</div>
	{% endif %}
</div>
	<div class="modality_field">
		<div style="display:none; float:left; line-height: 32px; width: 24px;">
			<div class="red_bubble modality_input_btn" style="display: inline-block;">v</div>
		</div>
		<div style="margin-left: 24px;">
			{{ search_form.modality }}
		</div>
	</div>
{#	{% if search_display_button %}#}
{#	<div class="highlight_container button_container combined_button_container" style="display: inline-block; box-shadow: none;">#}
{#		<span class="{% if search_display_type == 'list' %}selected{% endif %}">#}
{#			<a href="#" onclick="changeDisplayType('list')">L</a>#}
{#		</span><span class="{% if search_display_type == 'grid' %}selected{% endif %}">#}
{#			<a href="#" onclick="changeDisplayType('grid')">G</a>#}
{#		</span>#}
{#	</div>#}
{#	{% endif %}#}
<div id="modality_search" style="display: none;">
	<input type="text" class="modality_input_fb box_sizing" placeholder="Search Specialties"/>
	<p><a href="#" onclick="fb.end(); $('#search_form .modality_input').val('Any Specialty'); return false;">Any Specialty</a></p>
</div>

templates/about/search/results_grid.html
{% load pagination_tags %}
{% if not homepage_featured_centers %}
	{% autopaginate found_providers 24 %}
{% endif %}

{% with homepage_featured=True %}
<div class="friends">
	{% for provider in found_providers %}
		{% with provider.clientlocation_set.all.0.location as location %}
		{% with provider.distance as distance %}
		{% with provider.user as user %}
		{% with provider.modality_set.all as modalities %}
		{% with 140 as avatar_size %}
			<div class="grid_box grey_box">
			{% include "healers/friend_box.html" %}
			</div>
		{% endwith %}
		{% endwith %}
		{% endwith %}
		{% endwith %}
		{% endwith %}
	{% endfor %}
	{% if not homepage_featured_centers %}
		<div class="search_results_pagination">
			{% paginate %}
		</div>
	{% endif %}
</div>
{% include 'about/search/results_not_found.html' %}

{% endwith %}

templates/about/search/results_list.html
{% load healer_tags endless %}
{% if not all %}
	{% lazy_paginate found_providers with url_search %}
{% endif %}
<div class="friends">
	{% for healer in found_providers %}
		<div class="search_item">
			{% if not skip_first_hr or not forloop.first %}<hr />{% endif %}
			<a href="{{ healer.healer_profile_url }}" class="healer_full_profile_link"></a>
			<a href="{% url 'healer_info' healer.user.username %}" class="healer_profile_link floatbox" data-fb-options="type:ajax width:765"></a>

			<div class="grey_box search_results_provider">
				<div class="avatar_cell">{% with user=healer.user %}{% include "clients/avatar.html" %}{{ user.client }}{% endwith %}</div>
				<div class="info_cell">
					{{ healer.healer_under_profile_photo }}
					{% if healer.scheduleVisibility == 0 or healer.scheduleVisibility == 1 and request.user.is_authenticated %}
						<div style="margin-top: 14px;">
							{% include "healers/book_online_button.html" %}
						</div>
					{% endif %}
					{% if stats.providers_complete.count %}
						<div style="float: left; margin-top: 11px;">
							joined: <b>{{ healer.user.date_joined|date:"n/j/Y" }}</b>
							<br>
							{% if healer.signup_source %}{{ healer.signup_source }} - {% endif %}{{ healer.user.is_active|yesno:'ACT,UNC' }}
							<br>
							<i>{{ healer.get_step_name }}</i>
						</div>
					{% endif %}
				</div>
				<div class="specialties_cell wrap_normal">{{ healer.healer_specialties_html }}</div>
				<div class="about_cell wrap_normal">
					{% if phonegap %}
						<div>{{ healer.about|safe }}</div>
					{% else %}
						<div>{{ healer.about|hs_truncatewords_html:70|safe }}</div>
						<a href="{{ healer.healer_profile_url }}" class="read_more_link" style="display: none;">Read More &raquo;</a>
					{% endif %}
				</div>

			</div>
		</div>
	{% endfor %}
	{% show_more 'Show more &raquo;' %}

</div>
{% include 'about/search/results_not_found.html' %}

templates/about/search/results_not_found.html
{% if not found_providers %}
	{% if name_or_email or modality or request.GET.search_city_or_zipcode %} {# Did the user actually search or did they just browse to /search/ directly? #}
		<p class="message">Unfortunately, there are no {% if modality %}{{ modality }} {% endif %}Practitioners {% if request.GET.search_city_or_zipcode %}within 50 miles of {{ request.GET.search_city_or_zipcode }}{% endif %} yet.. Be the first to <a href="{% url 'signup' %}">Sign Up</a></p>
	{% endif %}
{% endif %}